### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by ps-groscoe**
Hello! On a recent dependabot run, I noticed that nalgebra <0.27.1 has a critical vulnerability. This PR updates the versions of serde and nalgebra to the latest, and changes the RealField trait to RealFieldCopy to mimic simba v0.5.1 behavior to make the crate build. I did look into updating quickcheck and rand, but it turned out to break the tests in a way where it wasn't clear whether the code or the test had the issue.

### CODE REVIEW

**Comment by feuerste** [comment]
@ps-groscoe Thanks for your contribution! Can you please also update the version number in the `README.md`?

**Comment by ps-groscoe** [comment]
@feuerste Certainly! I have just updated the version number. Please let me know if there is anything else you need before merging!

**Comment by feuerste** [comment]
Thanks @ps-groscoe for the update, looks good now!

**Comment by ps-groscoe** [comment]
@feuerste Awesome, thank you! Please let me know when the new version is published on crates.io

**Comment by feuerste** [comment]
It's also on crates.io now.

**Pull request merged**
